package fr.lip6.move.processGenerator.bpmn2;


public enum EBpmnElement {
	
	START_EVENT,
	END_EVENT,
	TASK,
	PARALLEL_GATEWAY_DIVERGING,
	PARALLEL_GATEWAY_CONVERGING,
	EXCLUSIVE_GATEWAY_DIVERGING,
	EXCLUSIVE_GATEWAY_CONVERGING
	
}
